[pytest]
filterwarnings =
    ignore::DeprecationWarning:daytona
testpaths = tests
python_files = test_*.py
python_functions = test_*
norecursedirs = .* venv node_modules
pythonpath = .
asyncio_default_fixture_loop_scope = function
addopts = -v --cov=getgather --cov-report=term-missing
markers =
    mcp: Tests for the MCP server.
    distill: Tests for the distillation functionality.
    api: Tests for the browser API.
