[project]
site_name = "Remote Browser"
site_url = "https://remotebrowser.ai/"
repo_url = "https://github.com/remotebrowser/remotebrowser"
repo_name = "remotebrowser/remotebrowser"
docs_dir = "docs"
site_dir = "site"
extra_css = ["stylesheets/font.css", "stylesheets/header.css", "stylesheets/sidebar.css"]
nav = [
  { "Overview" = "index.md" },
  { "Getting Started" = "getting-started.md" },
  { "Isolation" = "isolation.md" },
  { "Self-Hosting" = [
    { "Overview" = "self-hosting.md" },
    { "Controls" = "controls.md" },
    { "Sign-in" = "sign-in.md" },
    { "Database" = "database.md" },
    { "Instrumentation" = "instrumentation.md" },
  ] },
]

[project.theme]
language = "en"
font = false
custom_dir = "overrides"
features = [
  "content.code.copy",
  "navigation.footer",
  "navigation.instant",
  "navigation.sections",
  "search.highlight",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"

[project.markdown_extensions]
admonition = {}
attr_list = {}
toc.permalink = true
pymdownx.highlight = {}
pymdownx.superfences = {}
