import { Hono } from 'hono';
import { routes as home } from './homepage.js';
import { routes as signin } from './signin.js';
import { routes as sent } from './sent.js';
import { routes as continueRoutes } from './continue.js';
import { routes as browsersIndex } from './browsers/index.js';
import { routes as browsersLaunch } from './browsers/launch.js';
import { routes as browsersShow } from './browsers/show.js';
import { routes as browsersTerminate } from './browsers/terminate.js';
import { routes as browsersPagesIndex } from './browsers/pages/index.js';
import { routes as browsersPagesShow } from './browsers/pages/show.js';
import { routes as browsersPagesView } from './browsers/pages/view.js';
import { routes as workspacesIndex } from './workspaces/index.js';
import { routes as workspacesCreate } from './workspaces/create.js';
import { routes as workspacesSwitch } from './workspaces/switch.js';
import { routes as workspaceIndex } from './workspace/index.js';
import { routes as workspaceRole } from './workspace/role.js';
import { routes as workspaceRemove } from './workspace/remove.js';
import { routes as workspaceTransfer } from './workspace/transfer.js';
import { routes as workspaceInviteIndex } from './workspace/invite/index.js';
import { routes as workspaceInviteSent } from './workspace/invite/sent.js';
import { routes as workspaceDelete } from './workspace/delete.js';
import { routes as signout } from './signout.js';
import { routes as health } from './health.js';
import { routes as dev } from './dev.js';
import { routes as staticRoutes } from './static.js';

export const routes = new Hono();

routes.route('/', home);
routes.route('/signin', signin);
routes.route('/sent', sent);
routes.route('/continue', continueRoutes);
routes.route('/browsers', browsersIndex);
routes.route('/browsers', browsersLaunch);
routes.route('/browsers', browsersShow);
routes.route('/browsers', browsersTerminate);
routes.route('/browsers', browsersPagesIndex);
routes.route('/browsers', browsersPagesShow);
routes.route('/browsers', browsersPagesView);
routes.route('/workspaces', workspacesIndex);
routes.route('/workspaces', workspacesCreate);
routes.route('/workspaces', workspacesSwitch);
routes.route('/workspace', workspaceIndex);
routes.route('/workspace', workspaceRole);
routes.route('/workspace', workspaceRemove);
routes.route('/workspace', workspaceTransfer);
routes.route('/workspace/invite', workspaceInviteIndex);
routes.route('/workspace/invite', workspaceInviteSent);
routes.route('/workspace', workspaceDelete);
routes.route('/signout', signout);
routes.route('/health', health);
routes.route('/dev', dev);
routes.route('/', staticRoutes);
