CREATE TABLE signin_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_hash text NOT NULL UNIQUE,
  email text NOT NULL,
  expires_timestamp bigint NOT NULL
);

CREATE INDEX signin_codes_email_idx ON signin_codes (email);
CREATE UNIQUE INDEX users_email_unique_idx ON users (email);
