CREATE TABLE workspaces (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  owner_id bigint NOT NULL REFERENCES users(id),
  personal boolean NOT NULL DEFAULT false,
  CHECK (NOT personal OR name = 'Personal')
);

ALTER TABLE users
  ADD COLUMN personal_workspace_id bigint UNIQUE;

ALTER TABLE users
  ADD CONSTRAINT users_personal_workspace_fk
  FOREIGN KEY (personal_workspace_id) REFERENCES workspaces(id);

CREATE UNIQUE INDEX workspaces_one_personal_per_owner
  ON workspaces (owner_id)
  WHERE personal;
