CREATE TABLE collaborators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email text NOT NULL,
  role text NOT NULL CHECK (role IN ('Owner', 'Admin', 'User')),
  workspace_name text NOT NULL CHECK (char_length(workspace_name) BETWEEN 1 AND 80),
  UNIQUE (workspace_id, user_id)
);

CREATE INDEX collaborators_user_id_idx ON collaborators (user_id);

CREATE TABLE invitations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email text NOT NULL,
  role text NOT NULL CHECK (role = 'User'),
  workspace_name text NOT NULL CHECK (char_length(workspace_name) BETWEEN 1 AND 80),
  UNIQUE (workspace_id, email)
);

CREATE INDEX invitations_email_idx ON invitations (email);
