CREATE TABLE browser_instances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL CHECK (status IN ('starting', 'running', 'error', 'terminated')),
  user_id bigint NOT NULL REFERENCES users(id),
  workspace_id bigint NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  browser_name text NOT NULL CHECK (char_length(browser_name) BETWEEN 1 AND 80),
  browser_description text NOT NULL DEFAULT '' CHECK (char_length(browser_description) <= 140),
  internal_browser_id text NOT NULL DEFAULT '',
  browser_handle text NOT NULL,
  config jsonb
);

CREATE UNIQUE INDEX browser_instances_browser_handle_idx
  ON browser_instances (browser_handle);
